/* scetch.c generated by valac 0.42.5, the Vala compiler
 * generated from scetch.vala, do not modify */

/*
 * scetch.vala
 * 
 * Copyright 2021  <pi@raspberrypi>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */


#include <glib.h>
#include <glib-object.h>
#include <string.h>
#include <stdio.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <gobject/gvaluecollector.h>


#define TYPE_SLOT (slot_get_type ())
typedef struct _Slot Slot;

#define TYPE_DLOT (dlot_get_type ())
#define DLOT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DLOT, Dlot))
#define DLOT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DLOT, DlotClass))
#define IS_DLOT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DLOT))
#define IS_DLOT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DLOT))
#define DLOT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DLOT, DlotClass))

typedef struct _Dlot Dlot;
typedef struct _DlotClass DlotClass;
typedef struct _DlotPrivate DlotPrivate;
typedef struct _ParamSpecDlot ParamSpecDlot;
#define _dlot_unref0(var) ((var == NULL) ? NULL : (var = (dlot_unref (var), NULL)))

#define TYPE_FOO (foo_get_type ())
#define FOO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FOO, Foo))
#define FOO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FOO, FooClass))
#define IS_FOO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FOO))
#define IS_FOO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FOO))
#define FOO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FOO, FooClass))

typedef struct _Foo Foo;
typedef struct _FooClass FooClass;
typedef struct _FooPrivate FooPrivate;
enum  {
	FOO_0_PROPERTY,
	FOO_NUM_PROPERTIES
};
static GParamSpec* foo_properties[FOO_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Slot {
	guint8 underlyingNote;
	guint8* chord;
	gint chord_length1;
	gint _chord_size_;
};

struct _Dlot {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DlotPrivate * priv;
	guint8 underlyingNote;
	guint8* chord;
	gint chord_length1;
	gint _chord_size_;
};

struct _DlotClass {
	GTypeClass parent_class;
	void (*finalize) (Dlot *self);
};

struct _ParamSpecDlot {
	GParamSpec parent_instance;
};

struct _Foo {
	GObject parent_instance;
	FooPrivate * priv;
	gint bar;
};

struct _FooClass {
	GObjectClass parent_class;
};


static gpointer dlot_parent_class = NULL;
static gpointer foo_parent_class = NULL;

GType slot_get_type (void) G_GNUC_CONST;
Slot* slot_dup (const Slot* self);
void slot_free (Slot* self);
void slot_copy (const Slot* self,
                Slot* dest);
void slot_destroy (Slot* self);
static guint8* _vala_array_dup1 (guint8* self,
                          int length);
void make_slot (Slot* result);
gpointer dlot_ref (gpointer instance);
void dlot_unref (gpointer instance);
GParamSpec* param_spec_dlot (const gchar* name,
                             const gchar* nick,
                             const gchar* blurb,
                             GType object_type,
                             GParamFlags flags);
void value_set_dlot (GValue* value,
                     gpointer v_object);
void value_take_dlot (GValue* value,
                      gpointer v_object);
gpointer value_get_dlot (const GValue* value);
GType dlot_get_type (void) G_GNUC_CONST;
Dlot* dlot_new (void);
Dlot* dlot_construct (GType object_type);
static void dlot_finalize (Dlot * obj);
Dlot** return_dlots (gint count,
                     int* result_length1);
Dlot** dostuff (gint N,
                int* result_length1);
guint8* get_from_dlot (Dlot** dlots,
                       int dlots_length1,
                       gint which,
                       int* result_length1);
guint8* get_from_dlot2 (Dlot** dlots,
                        int dlots_length1,
                        gint which,
                        int* result_length1);
static guint8* _vala_array_dup2 (guint8* self,
                          int length);
void double_dumb (void);
static gdouble* _vala_array_dup3 (gdouble* self,
                           int length);
GType foo_get_type (void) G_GNUC_CONST;
gchar* foo_to_string (Foo* self);
Foo* foo_new (void);
Foo* foo_construct (GType object_type);
static void foo_finalize (GObject * obj);
gint _vala_main (gchar** args,
                 int args_length1);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);


static guint8*
_vala_array_dup1 (guint8* self,
                  int length)
{
	return g_memdup (self, length * sizeof (guint8));
}


void
slot_copy (const Slot* self,
           Slot* dest)
{
	guint8 _tmp0_;
	guint8* _tmp1_;
	gint _tmp1__length1;
	guint8* _tmp2_;
	gint _tmp2__length1;
	_tmp0_ = (*self).underlyingNote;
	(*dest).underlyingNote = _tmp0_;
	_tmp1_ = (*self).chord;
	_tmp1__length1 = (*self).chord_length1;
	_tmp2_ = (_tmp1_ != NULL) ? _vala_array_dup1 (_tmp1_, _tmp1__length1) : ((gpointer) _tmp1_);
	_tmp2__length1 = _tmp1__length1;
	(*dest).chord = (g_free ((*dest).chord), NULL);
	(*dest).chord = _tmp2_;
	(*dest).chord_length1 = _tmp2__length1;
	(*dest)._chord_size_ = (*dest).chord_length1;
}


void
slot_destroy (Slot* self)
{
	(*self).chord = (g_free ((*self).chord), NULL);
}


Slot*
slot_dup (const Slot* self)
{
	Slot* dup;
	dup = g_new0 (Slot, 1);
	slot_copy (self, dup);
	return dup;
}


void
slot_free (Slot* self)
{
	slot_destroy (self);
	g_free (self);
}


GType
slot_get_type (void)
{
	static volatile gsize slot_type_id__volatile = 0;
	if (g_once_init_enter (&slot_type_id__volatile)) {
		GType slot_type_id;
		slot_type_id = g_boxed_type_register_static ("Slot", (GBoxedCopyFunc) slot_dup, (GBoxedFreeFunc) slot_free);
		g_once_init_leave (&slot_type_id__volatile, slot_type_id);
	}
	return slot_type_id__volatile;
}


void
make_slot (Slot* result)
{
	guint8* _tmp0_;
	Slot _tmp1_ = {0};
	_tmp0_ = g_new0 (guint8, 3);
	_tmp0_[0] = (guint8) 2;
	_tmp0_[1] = (guint8) 3;
	_tmp0_[2] = (guint8) 4;
	memset (&_tmp1_, 0, sizeof (Slot));
	_tmp1_.underlyingNote = (guint8) 1;
	_tmp1_.chord = (g_free (_tmp1_.chord), NULL);
	_tmp1_.chord = _tmp0_;
	_tmp1_.chord_length1 = 3;
	_tmp1_._chord_size_ = _tmp1_.chord_length1;
	*result = _tmp1_;
	return;
}


Dlot*
dlot_construct (GType object_type)
{
	Dlot* self = NULL;
	self = (Dlot*) g_type_create_instance (object_type);
	return self;
}


Dlot*
dlot_new (void)
{
	return dlot_construct (TYPE_DLOT);
}


static void
value_dlot_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}


static void
value_dlot_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		dlot_unref (value->data[0].v_pointer);
	}
}


static void
value_dlot_copy_value (const GValue* src_value,
                       GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = dlot_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer
value_dlot_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}


static gchar*
value_dlot_collect_value (GValue* value,
                          guint n_collect_values,
                          GTypeCValue* collect_values,
                          guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		Dlot * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = dlot_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar*
value_dlot_lcopy_value (const GValue* value,
                        guint n_collect_values,
                        GTypeCValue* collect_values,
                        guint collect_flags)
{
	Dlot ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = dlot_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec*
param_spec_dlot (const gchar* name,
                 const gchar* nick,
                 const gchar* blurb,
                 GType object_type,
                 GParamFlags flags)
{
	ParamSpecDlot* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_DLOT), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer
value_get_dlot (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_DLOT), NULL);
	return value->data[0].v_pointer;
}


void
value_set_dlot (GValue* value,
                gpointer v_object)
{
	Dlot * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_DLOT));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_DLOT));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		dlot_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		dlot_unref (old);
	}
}


void
value_take_dlot (GValue* value,
                 gpointer v_object)
{
	Dlot * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_DLOT));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_DLOT));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		dlot_unref (old);
	}
}


static void
dlot_class_init (DlotClass * klass)
{
	dlot_parent_class = g_type_class_peek_parent (klass);
	((DlotClass *) klass)->finalize = dlot_finalize;
}


static void
dlot_instance_init (Dlot * self)
{
	guint8* _tmp0_;
	self->underlyingNote = (guint8) 123;
	_tmp0_ = g_new0 (guint8, 1);
	_tmp0_[0] = (guint8) 4;
	self->chord = _tmp0_;
	self->chord_length1 = 1;
	self->_chord_size_ = self->chord_length1;
	self->ref_count = 1;
}


static void
dlot_finalize (Dlot * obj)
{
	Dlot * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DLOT, Dlot);
	g_signal_handlers_destroy (self);
	self->chord = (g_free (self->chord), NULL);
}


GType
dlot_get_type (void)
{
	static volatile gsize dlot_type_id__volatile = 0;
	if (g_once_init_enter (&dlot_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_dlot_init, value_dlot_free_value, value_dlot_copy_value, value_dlot_peek_pointer, "p", value_dlot_collect_value, "p", value_dlot_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (DlotClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dlot_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Dlot), 0, (GInstanceInitFunc) dlot_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType dlot_type_id;
		dlot_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Dlot", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&dlot_type_id__volatile, dlot_type_id);
	}
	return dlot_type_id__volatile;
}


gpointer
dlot_ref (gpointer instance)
{
	Dlot * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void
dlot_unref (gpointer instance)
{
	Dlot * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		DLOT_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static gpointer
_dlot_ref0 (gpointer self)
{
	return self ? dlot_ref (self) : NULL;
}


Dlot**
return_dlots (gint count,
              int* result_length1)
{
	Dlot** result = NULL;
	Dlot** a = NULL;
	Dlot** _tmp0_;
	gint a_length1;
	gint _a_size_;
	Dlot** _tmp13_;
	gint _tmp13__length1;
	_tmp0_ = g_new0 (Dlot*, count + 1);
	a = _tmp0_;
	a_length1 = count;
	_a_size_ = a_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gint _tmp3_;
				Dlot* d = NULL;
				Dlot* _tmp4_;
				Dlot* _tmp5_;
				gint _tmp6_;
				Dlot* _tmp7_;
				guint8* _tmp8_;
				Dlot** _tmp9_;
				gint _tmp9__length1;
				gint _tmp10_;
				Dlot* _tmp11_;
				Dlot* _tmp12_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp3_ = i;
				if (!(_tmp3_ < count)) {
					break;
				}
				_tmp4_ = dlot_new ();
				d = _tmp4_;
				_tmp5_ = d;
				_tmp6_ = i;
				_tmp5_->underlyingNote = (guint8) (((guint8) _tmp6_) % 8);
				_tmp7_ = d;
				_tmp8_ = g_new0 (guint8, 6);
				_tmp8_[0] = (guint8) 3;
				_tmp8_[1] = (guint8) 4;
				_tmp8_[2] = (guint8) 5;
				_tmp8_[3] = (guint8) 6;
				_tmp8_[4] = (guint8) 7;
				_tmp8_[5] = (guint8) 8;
				_tmp7_->chord = (g_free (_tmp7_->chord), NULL);
				_tmp7_->chord = _tmp8_;
				_tmp7_->chord_length1 = 6;
				_tmp7_->_chord_size_ = _tmp7_->chord_length1;
				_tmp9_ = a;
				_tmp9__length1 = a_length1;
				_tmp10_ = i;
				_tmp11_ = d;
				_tmp12_ = _dlot_ref0 (_tmp11_);
				_dlot_unref0 (_tmp9_[_tmp10_]);
				_tmp9_[_tmp10_] = _tmp12_;
				_dlot_unref0 (d);
			}
		}
	}
	_tmp13_ = a;
	_tmp13__length1 = a_length1;
	if (result_length1) {
		*result_length1 = _tmp13__length1;
	}
	result = _tmp13_;
	return result;
}


Dlot**
dostuff (gint N,
         int* result_length1)
{
	Dlot** result = NULL;
	Dlot** dlots = NULL;
	gint _tmp0_ = 0;
	Dlot** _tmp1_;
	gint dlots_length1;
	gint _dlots_size_;
	Dlot** _tmp2_;
	gint _tmp2__length1;
	Dlot** _tmp9_;
	gint _tmp9__length1;
	_tmp1_ = return_dlots (N, &_tmp0_);
	dlots = _tmp1_;
	dlots_length1 = _tmp0_;
	_dlots_size_ = dlots_length1;
	_tmp2_ = dlots;
	_tmp2__length1 = dlots_length1;
	{
		Dlot** d_collection = NULL;
		gint d_collection_length1 = 0;
		gint _d_collection_size_ = 0;
		gint d_it = 0;
		d_collection = _tmp2_;
		d_collection_length1 = _tmp2__length1;
		for (d_it = 0; d_it < _tmp2__length1; d_it = d_it + 1) {
			Dlot* d = NULL;
			d = d_collection[d_it];
			{
				FILE* _tmp3_;
				Dlot* _tmp4_;
				guint8 _tmp5_;
				Dlot* _tmp6_;
				guint8* _tmp7_;
				gint _tmp7__length1;
				guint8 _tmp8_;
				_tmp3_ = stdout;
				_tmp4_ = d;
				_tmp5_ = _tmp4_->underlyingNote;
				_tmp6_ = d;
				_tmp7_ = _tmp6_->chord;
				_tmp7__length1 = _tmp6_->chord_length1;
				_tmp8_ = _tmp7_[0];
				fprintf (_tmp3_, "AA %d BB %d\n", (gint) _tmp5_, (gint) _tmp8_);
			}
		}
	}
	_tmp9_ = dlots;
	_tmp9__length1 = dlots_length1;
	if (result_length1) {
		*result_length1 = _tmp9__length1;
	}
	result = _tmp9_;
	return result;
}


guint8*
get_from_dlot (Dlot** dlots,
               int dlots_length1,
               gint which,
               int* result_length1)
{
	guint8* result = NULL;
	Dlot* _tmp0_;
	guint8* _tmp1_;
	gint _tmp1__length1;
	guint8* _tmp2_;
	gint _tmp2__length1;
	_tmp0_ = dlots[which];
	_tmp1_ = _tmp0_->chord;
	_tmp1__length1 = _tmp0_->chord_length1;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp1__length1;
	if (result_length1) {
		*result_length1 = _tmp2__length1;
	}
	result = _tmp2_;
	return result;
}


static guint8*
_vala_array_dup2 (guint8* self,
                  int length)
{
	return g_memdup (self, length * sizeof (guint8));
}


guint8*
get_from_dlot2 (Dlot** dlots,
                int dlots_length1,
                gint which,
                int* result_length1)
{
	guint8* result = NULL;
	Dlot* _tmp0_;
	guint8* _tmp1_;
	gint _tmp1__length1;
	guint8* _tmp2_;
	gint _tmp2__length1;
	guint8* _tmp3_;
	gint _tmp3__length1;
	_tmp0_ = dlots[which];
	_tmp1_ = _tmp0_->chord;
	_tmp1__length1 = _tmp0_->chord_length1;
	_tmp2_ = (_tmp1_ != NULL) ? _vala_array_dup2 (_tmp1_, _tmp1__length1) : ((gpointer) _tmp1_);
	_tmp2__length1 = _tmp1__length1;
	_tmp3_ = _tmp2_;
	_tmp3__length1 = _tmp2__length1;
	if (result_length1) {
		*result_length1 = _tmp3__length1;
	}
	result = _tmp3_;
	return result;
}


static gdouble*
_vala_array_dup3 (gdouble* self,
                  int length)
{
	return g_memdup (self, length * sizeof (gdouble));
}


void
double_dumb (void)
{
	gdouble* d1 = NULL;
	gdouble* _tmp0_;
	gint d1_length1;
	gint _d1_size_;
	gdouble* d2 = NULL;
	gdouble* _tmp1_;
	gint _tmp1__length1;
	gdouble* _tmp2_;
	gint _tmp2__length1;
	gint d2_length1;
	gint _d2_size_;
	_tmp0_ = g_new0 (gdouble, 4);
	_tmp0_[0] = (gdouble) 1;
	_tmp0_[1] = (gdouble) 2;
	_tmp0_[2] = (gdouble) 3;
	_tmp0_[3] = (gdouble) 4;
	d1 = _tmp0_;
	d1_length1 = 4;
	_d1_size_ = d1_length1;
	_tmp1_ = d1;
	_tmp1__length1 = d1_length1;
	_tmp2_ = (_tmp1_ != NULL) ? _vala_array_dup3 (_tmp1_, _tmp1__length1) : ((gpointer) _tmp1_);
	_tmp2__length1 = _tmp1__length1;
	d2 = _tmp2_;
	d2_length1 = _tmp2__length1;
	_d2_size_ = d2_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp3_ = FALSE;
			_tmp3_ = TRUE;
			while (TRUE) {
				gint _tmp5_;
				gdouble* _tmp6_;
				gint _tmp6__length1;
				FILE* _tmp7_;
				gdouble* _tmp8_;
				gint _tmp8__length1;
				gint _tmp9_;
				gdouble _tmp10_;
				gdouble* _tmp11_;
				gint _tmp11__length1;
				gint _tmp12_;
				gdouble _tmp13_;
				if (!_tmp3_) {
					gint _tmp4_;
					_tmp4_ = i;
					i = _tmp4_ + 1;
				}
				_tmp3_ = FALSE;
				_tmp5_ = i;
				_tmp6_ = d2;
				_tmp6__length1 = d2_length1;
				if (!(_tmp5_ < _tmp6__length1)) {
					break;
				}
				_tmp7_ = stdout;
				_tmp8_ = d1;
				_tmp8__length1 = d1_length1;
				_tmp9_ = i;
				_tmp10_ = _tmp8_[_tmp9_];
				_tmp11_ = d2;
				_tmp11__length1 = d2_length1;
				_tmp12_ = i;
				_tmp13_ = _tmp11_[_tmp12_];
				fprintf (_tmp7_, "QQ %f %f\n", _tmp10_, 2 * _tmp13_);
			}
		}
	}
	d2 = (g_free (d2), NULL);
	d1 = (g_free (d1), NULL);
}


gchar*
foo_to_string (Foo* self)
{
	gchar* result = NULL;
	gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup ("text stuff");
	result = _tmp0_;
	return result;
}


Foo*
foo_construct (GType object_type)
{
	Foo * self = NULL;
	self = (Foo*) g_object_new (object_type, NULL);
	return self;
}


Foo*
foo_new (void)
{
	return foo_construct (TYPE_FOO);
}


static void
foo_class_init (FooClass * klass)
{
	foo_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = foo_finalize;
}


static void
foo_instance_init (Foo * self)
{
	self->bar = 0;
}


static void
foo_finalize (GObject * obj)
{
	Foo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_FOO, Foo);
	G_OBJECT_CLASS (foo_parent_class)->finalize (obj);
}


GType
foo_get_type (void)
{
	static volatile gsize foo_type_id__volatile = 0;
	if (g_once_init_enter (&foo_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FooClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) foo_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Foo), 0, (GInstanceInitFunc) foo_instance_init, NULL };
		GType foo_type_id;
		foo_type_id = g_type_register_static (G_TYPE_OBJECT, "Foo", &g_define_type_info, 0);
		g_once_init_leave (&foo_type_id__volatile, foo_type_id);
	}
	return foo_type_id__volatile;
}


gint
_vala_main (gchar** args,
            int args_length1)
{
	gint result = 0;
	Foo* f = NULL;
	Foo* _tmp0_;
	FILE* _tmp1_;
	Foo* _tmp2_;
	gint _tmp3_;
	Foo* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* s1 = NULL;
	gchar* _tmp7_;
	gchar* s11 = NULL;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* s2 = NULL;
	gchar* _tmp10_;
	gchar* s3 = NULL;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	const gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	FILE* _tmp17_;
	const gchar* _tmp18_;
	const gchar* _tmp19_;
	gdouble* d = NULL;
	gdouble* _tmp20_;
	gint d_length1;
	gint _d_size_;
	Slot slt = {0};
	Slot _tmp32_ = {0};
	FILE* _tmp33_;
	Slot _tmp34_;
	guint8* _tmp35_;
	gint _tmp35__length1;
	guint8 _tmp36_;
	_tmp0_ = foo_new ();
	f = _tmp0_;
	_tmp1_ = stdout;
	_tmp2_ = f;
	_tmp3_ = _tmp2_->bar;
	_tmp4_ = f;
	_tmp5_ = foo_to_string (_tmp4_);
	_tmp6_ = _tmp5_;
	fprintf (_tmp1_, "f.bar = %d (%s)\n", _tmp3_, _tmp6_);
	_g_free0 (_tmp6_);
	_tmp7_ = g_strdup ("Hello");
	s1 = _tmp7_;
	_tmp8_ = s1;
	_tmp9_ = g_strdup (_tmp8_);
	s11 = _tmp9_;
	_tmp10_ = g_strdup ("Wourld");
	s2 = _tmp10_;
	_tmp11_ = s1;
	_tmp12_ = g_strconcat (_tmp11_, " ", NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = s2;
	_tmp15_ = g_strconcat (_tmp13_, _tmp14_, NULL);
	_tmp16_ = _tmp15_;
	_g_free0 (_tmp13_);
	s3 = _tmp16_;
	_tmp17_ = stdout;
	_tmp18_ = s3;
	_tmp19_ = s11;
	fprintf (_tmp17_, "The result is %s %s\n", _tmp18_, _tmp19_);
	_tmp20_ = g_new0 (gdouble, 20);
	d = _tmp20_;
	d_length1 = 20;
	_d_size_ = d_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp21_ = FALSE;
			_tmp21_ = TRUE;
			while (TRUE) {
				gint _tmp23_;
				gdouble* _tmp24_;
				gint _tmp24__length1;
				gdouble* _tmp25_;
				gint _tmp25__length1;
				gint _tmp26_;
				gint _tmp27_;
				FILE* _tmp28_;
				gdouble* _tmp29_;
				gint _tmp29__length1;
				gint _tmp30_;
				gdouble _tmp31_;
				if (!_tmp21_) {
					gint _tmp22_;
					_tmp22_ = i;
					i = _tmp22_ + 1;
				}
				_tmp21_ = FALSE;
				_tmp23_ = i;
				_tmp24_ = d;
				_tmp24__length1 = d_length1;
				if (!(_tmp23_ < _tmp24__length1)) {
					break;
				}
				_tmp25_ = d;
				_tmp25__length1 = d_length1;
				_tmp26_ = i;
				_tmp27_ = i;
				_tmp25_[_tmp26_] = (5.0 * _tmp27_) + 56;
				_tmp28_ = stdout;
				_tmp29_ = d;
				_tmp29__length1 = d_length1;
				_tmp30_ = i;
				_tmp31_ = _tmp29_[_tmp30_];
				fprintf (_tmp28_, ">> %f\n", _tmp31_);
			}
		}
	}
	make_slot (&_tmp32_);
	slt = _tmp32_;
	_tmp33_ = stdout;
	_tmp34_ = slt;
	_tmp35_ = _tmp34_.chord;
	_tmp35__length1 = _tmp34_.chord_length1;
	_tmp36_ = _tmp35_[0];
	fprintf (_tmp33_, ">> %d\n", (gint) _tmp36_);
	result = 0;
	slot_destroy (&slt);
	d = (g_free (d), NULL);
	_g_free0 (s3);
	_g_free0 (s2);
	_g_free0 (s11);
	_g_free0 (s1);
	_g_object_unref0 (f);
	return result;
}


int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}


static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



