/* ValaSequencerExample.c generated by valac 0.42.5, the Vala compiler
 * generated from ValaSequencerExample.vala, do not modify */

/*int snd_seq_parse_address(snd_seq_t *seq, snd_seq_addr_t *addr, const char *arg);*/


#include <glib.h>
#include <glib-object.h>
#include <alsa/asoundlib.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <stdio.h>
#include <poll.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _0(var) ((var == NULL) ? NULL : (var = ( (var), NULL)))
#define _snd_seq_free_event0(var) ((var == NULL) ? NULL : (var = (snd_seq_free_event (var), NULL)))



gint snd_seq_parse_address (snd_seq_t* seq,
                            snd_seq_addr_t* addr,
                            const gchar* arg);
void checkResultAndExitIfNecessary (const gchar* msg,
                                    gint _result_);
void dumpMidiEvent (snd_seq_event_t* event);
const gchar* snd_seq_event_type_to_string (snd_seq_event_type_t self);
static const char* _snd_seq_event_type_to_string (snd_seq_event_type_t value);
gint _vala_main (gchar** args,
                 int args_length1);
gint main_old (gchar** args,
               int args_length1);


static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


void
checkResultAndExitIfNecessary (const gchar* msg,
                               gint _result_)
{
	g_return_if_fail (msg != NULL);
	if (_result_ < 0) {
		const gchar* _tmp0_;
		gint _tmp1_;
		const gchar* _tmp2_;
		const gchar* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
		_tmp0_ = string_to_string (msg);
		_tmp1_ = errno;
		_tmp2_ = g_strerror (_tmp1_);
		_tmp3_ = string_to_string (_tmp2_);
		_tmp4_ = g_strconcat (_tmp0_, " FAIL: ", _tmp3_, NULL);
		_tmp5_ = _tmp4_;
		g_error ("ValaSequencerExample.vala:11: %s", _tmp5_);
		_g_free0 (_tmp5_);
		exit (-1);
	} else {
		const gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		_tmp6_ = string_to_string (msg);
		_tmp7_ = g_strconcat (_tmp6_, " OK", NULL);
		_tmp8_ = _tmp7_;
		g_message ("ValaSequencerExample.vala:16: %s", _tmp8_);
		_g_free0 (_tmp8_);
	}
}


static const char*
_snd_seq_event_type_to_string (snd_seq_event_type_t value)
{
	switch (value) {
		case SND_SEQ_EVENT_SYSTEM:
		return "SND_SEQ_EVENT_SYSTEM";
		case SND_SEQ_EVENT_RESULT:
		return "SND_SEQ_EVENT_RESULT";
		case SND_SEQ_EVENT_NOTE:
		return "SND_SEQ_EVENT_NOTE";
		case SND_SEQ_EVENT_NOTEON:
		return "SND_SEQ_EVENT_NOTEON";
		case SND_SEQ_EVENT_NOTEOFF:
		return "SND_SEQ_EVENT_NOTEOFF";
		case SND_SEQ_EVENT_KEYPRESS:
		return "SND_SEQ_EVENT_KEYPRESS";
		case SND_SEQ_EVENT_CONTROLLER:
		return "SND_SEQ_EVENT_CONTROLLER";
		case SND_SEQ_EVENT_PGMCHANGE:
		return "SND_SEQ_EVENT_PGMCHANGE";
		case SND_SEQ_EVENT_CHANPRESS:
		return "SND_SEQ_EVENT_CHANPRESS";
		case SND_SEQ_EVENT_PITCHBEND:
		return "SND_SEQ_EVENT_PITCHBEND";
		case SND_SEQ_EVENT_CONTROL14:
		return "SND_SEQ_EVENT_CONTROL14";
		case SND_SEQ_EVENT_NONREGPARAM:
		return "SND_SEQ_EVENT_NONREGPARAM";
		case SND_SEQ_EVENT_REGPARAM:
		return "SND_SEQ_EVENT_REGPARAM";
		case SND_SEQ_EVENT_SONGPOS:
		return "SND_SEQ_EVENT_SONGPOS";
		case SND_SEQ_EVENT_SONGSEL:
		return "SND_SEQ_EVENT_SONGSEL";
		case SND_SEQ_EVENT_QFRAME:
		return "SND_SEQ_EVENT_QFRAME";
		case SND_SEQ_EVENT_TIMESIGN:
		return "SND_SEQ_EVENT_TIMESIGN";
		case SND_SEQ_EVENT_KEYSIGN:
		return "SND_SEQ_EVENT_KEYSIGN";
		case SND_SEQ_EVENT_START:
		return "SND_SEQ_EVENT_START";
		case SND_SEQ_EVENT_CONTINUE:
		return "SND_SEQ_EVENT_CONTINUE";
		case SND_SEQ_EVENT_STOP:
		return "SND_SEQ_EVENT_STOP";
		case SND_SEQ_EVENT_SETPOS_TICK:
		return "SND_SEQ_EVENT_SETPOS_TICK";
		case SND_SEQ_EVENT_SETPOS_TIME:
		return "SND_SEQ_EVENT_SETPOS_TIME";
		case SND_SEQ_EVENT_TEMPO:
		return "SND_SEQ_EVENT_TEMPO";
		case SND_SEQ_EVENT_CLOCK:
		return "SND_SEQ_EVENT_CLOCK";
		case SND_SEQ_EVENT_TICK:
		return "SND_SEQ_EVENT_TICK";
		case SND_SEQ_EVENT_QUEUE_SKEW:
		return "SND_SEQ_EVENT_QUEUE_SKEW";
		case SND_SEQ_EVENT_SYNC_POS:
		return "SND_SEQ_EVENT_SYNC_POS";
		case SND_SEQ_EVENT_TUNE_REQUEST:
		return "SND_SEQ_EVENT_TUNE_REQUEST";
		case SND_SEQ_EVENT_RESET:
		return "SND_SEQ_EVENT_RESET";
		case SND_SEQ_EVENT_SENSING:
		return "SND_SEQ_EVENT_SENSING";
		case SND_SEQ_EVENT_ECHO:
		return "SND_SEQ_EVENT_ECHO";
		case SND_SEQ_EVENT_OSS:
		return "SND_SEQ_EVENT_OSS";
		case SND_SEQ_EVENT_CLIENT_START:
		return "SND_SEQ_EVENT_CLIENT_START";
		case SND_SEQ_EVENT_CLIENT_EXIT:
		return "SND_SEQ_EVENT_CLIENT_EXIT";
		case SND_SEQ_EVENT_CLIENT_CHANGE:
		return "SND_SEQ_EVENT_CLIENT_CHANGE";
		case SND_SEQ_EVENT_PORT_START:
		return "SND_SEQ_EVENT_PORT_START";
		case SND_SEQ_EVENT_PORT_EXIT:
		return "SND_SEQ_EVENT_PORT_EXIT";
		case SND_SEQ_EVENT_PORT_CHANGE:
		return "SND_SEQ_EVENT_PORT_CHANGE";
		case SND_SEQ_EVENT_PORT_SUBSCRIBED:
		return "SND_SEQ_EVENT_PORT_SUBSCRIBED";
		case SND_SEQ_EVENT_PORT_UNSUBSCRIBED:
		return "SND_SEQ_EVENT_PORT_UNSUBSCRIBED";
		case SND_SEQ_EVENT_USR0:
		return "SND_SEQ_EVENT_USR0";
		case SND_SEQ_EVENT_USR1:
		return "SND_SEQ_EVENT_USR1";
		case SND_SEQ_EVENT_USR2:
		return "SND_SEQ_EVENT_USR2";
		case SND_SEQ_EVENT_USR3:
		return "SND_SEQ_EVENT_USR3";
		case SND_SEQ_EVENT_USR4:
		return "SND_SEQ_EVENT_USR4";
		case SND_SEQ_EVENT_USR5:
		return "SND_SEQ_EVENT_USR5";
		case SND_SEQ_EVENT_USR6:
		return "SND_SEQ_EVENT_USR6";
		case SND_SEQ_EVENT_USR7:
		return "SND_SEQ_EVENT_USR7";
		case SND_SEQ_EVENT_USR8:
		return "SND_SEQ_EVENT_USR8";
		case SND_SEQ_EVENT_USR9:
		return "SND_SEQ_EVENT_USR9";
		case SND_SEQ_EVENT_SYSEX:
		return "SND_SEQ_EVENT_SYSEX";
		case SND_SEQ_EVENT_BOUNCE:
		return "SND_SEQ_EVENT_BOUNCE";
		case SND_SEQ_EVENT_USR_VAR0:
		return "SND_SEQ_EVENT_USR_VAR0";
		case SND_SEQ_EVENT_USR_VAR1:
		return "SND_SEQ_EVENT_USR_VAR1";
		case SND_SEQ_EVENT_USR_VAR2:
		return "SND_SEQ_EVENT_USR_VAR2";
		case SND_SEQ_EVENT_USR_VAR3:
		return "SND_SEQ_EVENT_USR_VAR3";
		case SND_SEQ_EVENT_USR_VAR4:
		return "SND_SEQ_EVENT_USR_VAR4";
		case SND_SEQ_EVENT_NONE:
		return "SND_SEQ_EVENT_NONE";
	}
	return NULL;
}


void
dumpMidiEvent (snd_seq_event_t* event)
{
	snd_seq_event_type_t _tmp0_;
	g_return_if_fail (event != NULL);
	_tmp0_ = event->type;
	switch (_tmp0_) {
		case SND_SEQ_EVENT_CONTROLLER:
		{
			snd_seq_ev_ctrl_t _tmp1_;
			guint8 _tmp2_;
			snd_seq_ev_ctrl_t _tmp3_;
			gint _tmp4_;
			_tmp1_ = event->data.control;
			_tmp2_ = _tmp1_.channel;
			_tmp3_ = event->data.control;
			_tmp4_ = _tmp3_.value;
			g_print ("Control event on Channel %2d: %5d\n", (gint) _tmp2_, _tmp4_);
			break;
		}
		case SND_SEQ_EVENT_PITCHBEND:
		{
			snd_seq_ev_ctrl_t _tmp5_;
			guint8 _tmp6_;
			snd_seq_ev_ctrl_t _tmp7_;
			gint _tmp8_;
			_tmp5_ = event->data.control;
			_tmp6_ = _tmp5_.channel;
			_tmp7_ = event->data.control;
			_tmp8_ = _tmp7_.value;
			g_print ("Pitchbender event on Channel %2d: %5d\n", (gint) _tmp6_, _tmp8_);
			break;
		}
		case SND_SEQ_EVENT_NOTEON:
		{
			snd_seq_ev_ctrl_t _tmp9_;
			guint8 _tmp10_;
			snd_seq_ev_note_t _tmp11_;
			guint8 _tmp12_;
			_tmp9_ = event->data.control;
			_tmp10_ = _tmp9_.channel;
			_tmp11_ = event->data.note;
			_tmp12_ = _tmp11_.note;
			g_print ("Note On event on Channel %2d: %5d\n", (gint) _tmp10_, (gint) _tmp12_);
			break;
		}
		case SND_SEQ_EVENT_NOTEOFF:
		{
			snd_seq_ev_ctrl_t _tmp13_;
			guint8 _tmp14_;
			snd_seq_ev_note_t _tmp15_;
			guint8 _tmp16_;
			_tmp13_ = event->data.control;
			_tmp14_ = _tmp13_.channel;
			_tmp15_ = event->data.note;
			_tmp16_ = _tmp15_.note;
			g_print ("Note Off event on Channel %2d: %5d\n", (gint) _tmp14_, (gint) _tmp16_);
			break;
		}
		case SND_SEQ_EVENT_PORT_SUBSCRIBED:
		{
			snd_seq_connect_t _tmp17_;
			snd_seq_addr_t _tmp18_;
			guint8 _tmp19_;
			snd_seq_connect_t _tmp20_;
			snd_seq_addr_t _tmp21_;
			guint8 _tmp22_;
			snd_seq_connect_t _tmp23_;
			snd_seq_addr_t _tmp24_;
			guint8 _tmp25_;
			snd_seq_connect_t _tmp26_;
			snd_seq_addr_t _tmp27_;
			guint8 _tmp28_;
			_tmp17_ = event->data.connect;
			_tmp18_ = _tmp17_.sender;
			_tmp19_ = _tmp18_.client;
			_tmp20_ = event->data.connect;
			_tmp21_ = _tmp20_.sender;
			_tmp22_ = _tmp21_.port;
			_tmp23_ = event->data.connect;
			_tmp24_ = _tmp23_.dest;
			_tmp25_ = _tmp24_.client;
			_tmp26_ = event->data.connect;
			_tmp27_ = _tmp26_.dest;
			_tmp28_ = _tmp27_.port;
			g_print ("Port subscribed. %u:%u -> %u:%u\n", (guint) _tmp19_, (guint) _tmp22_, (guint) _tmp25_, (guint) _tmp28_);
			break;
		}
		default:
		{
			snd_seq_event_type_t _tmp29_;
			const gchar* _tmp30_;
			gchar* _tmp31_;
			gchar* _tmp32_;
			_tmp29_ = event->type;
			_tmp30_ = _snd_seq_event_type_to_string (_tmp29_);
			_tmp31_ = g_strconcat ("Ignoring unrecognized event: ", _tmp30_, "\n", NULL);
			_tmp32_ = _tmp31_;
			g_print ("%s", _tmp32_);
			_g_free0 (_tmp32_);
			break;
		}
	}
}


gint
_vala_main (gchar** args,
            int args_length1)
{
	gint result = 0;
	snd_seq_t* device = NULL;
	gint ok = 0;
	snd_seq_t* _tmp0_ = NULL;
	gint _tmp1_;
	gint _tmp2_;
	snd_seq_addr_t addr = {0};
	snd_seq_addr_t _tmp3_ = {0};
	snd_seq_addr_t _tmp4_ = {0};
	gint _tmp5_;
	gint _tmp6_;
	FILE* _tmp7_;
	snd_seq_addr_t _tmp8_;
	guint8 _tmp9_;
	snd_seq_addr_t _tmp10_;
	guint8 _tmp11_;
	_tmp1_ = snd_seq_open (&_tmp0_, "hw", SND_SEQ_OPEN_DUPLEX, 0);
	_0 (device);
	device = _tmp0_;
	ok = _tmp1_;
	_tmp2_ = ok;
	checkResultAndExitIfNecessary ("Open sequencer", _tmp2_);
	_tmp3_.client = (guint8) 0;
	_tmp3_.port = (guint8) 0;
	addr = _tmp3_;
	_tmp5_ = snd_seq_parse_address (device, &_tmp4_, "FANTOM");
	addr = _tmp4_;
	ok = _tmp5_;
	_tmp6_ = ok;
	checkResultAndExitIfNecessary ("parse address", _tmp6_);
	_tmp7_ = stdout;
	_tmp8_ = addr;
	_tmp9_ = _tmp8_.client;
	_tmp10_ = addr;
	_tmp11_ = _tmp10_.port;
	fprintf (_tmp7_, "CLIENT:PORT     %d:%d\n", (gint) _tmp9_, (gint) _tmp11_);
	result = 0;
	_0 (device);
	return result;
}


int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}


gint
main_old (gchar** args,
          int args_length1)
{
	gint result = 0;
	snd_seq_t* device = NULL;
	gint ok = 0;
	snd_seq_t* _tmp0_ = NULL;
	gint _tmp1_;
	gint _tmp2_;
	snd_seq_addr_t addr = {0};
	snd_seq_addr_t _tmp3_ = {0};
	snd_seq_addr_t _tmp4_;
	FILE* _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
	FILE* _tmp8_;
	snd_seq_addr_t _tmp9_;
	guint8 _tmp10_;
	snd_seq_addr_t _tmp11_;
	guint8 _tmp12_;
	gint npfd = 0;
	struct pollfd* pfd = NULL;
	gint _tmp13_;
	struct pollfd* _tmp14_;
	gint pfd_length1;
	gint _pfd_size_;
	struct pollfd* _tmp15_;
	gint _tmp15__length1;
	gint _tmp16_;
	_tmp1_ = snd_seq_open (&_tmp0_, "hw", SND_SEQ_OPEN_DUPLEX, 0);
	_0 (device);
	device = _tmp0_;
	ok = _tmp1_;
	_tmp2_ = ok;
	checkResultAndExitIfNecessary ("Open sequencer", _tmp2_);
	snd_seq_set_client_name (device, "Vala MIDI Demo");
	_tmp3_.client = (guint8) 0;
	_tmp3_.port = (guint8) 0;
	addr = _tmp3_;
	_tmp4_ = addr;
	ok = snd_seq_parse_address (device, &_tmp4_, "xFANTOM");
	_tmp5_ = stdout;
	_tmp6_ = ok;
	fprintf (_tmp5_, "RESULT %d\n", _tmp6_);
	_tmp7_ = ok;
	checkResultAndExitIfNecessary ("fantom ", _tmp7_);
	_tmp8_ = stdout;
	_tmp9_ = addr;
	_tmp10_ = _tmp9_.client;
	_tmp11_ = addr;
	_tmp12_ = _tmp11_.port;
	fprintf (_tmp8_, "CLIENT %d and PORT %d\n", (gint) _tmp10_, (gint) _tmp12_);
	result = 0;
	_0 (device);
	return result;
	npfd = snd_seq_poll_descriptors_count (device, POLLIN);
	_tmp13_ = npfd;
	_tmp14_ = g_new0 (struct pollfd, _tmp13_);
	pfd = _tmp14_;
	pfd_length1 = _tmp13_;
	_pfd_size_ = pfd_length1;
	_tmp15_ = pfd;
	_tmp15__length1 = pfd_length1;
	ok = snd_seq_poll_descriptors (device, _tmp15_, _tmp15__length1, POLLIN);
	_tmp16_ = ok;
	checkResultAndExitIfNecessary ("Get poll descriptors", _tmp16_);
	while (TRUE) {
		snd_seq_event_t* event = NULL;
		struct pollfd* _tmp17_;
		gint _tmp17__length1;
		_tmp17_ = pfd;
		_tmp17__length1 = pfd_length1;
		if (poll (_tmp17_, _tmp17__length1, 100000) > 0) {
			{
				gboolean _tmp18_ = FALSE;
				_tmp18_ = TRUE;
				while (TRUE) {
					snd_seq_event_t* _tmp19_ = NULL;
					snd_seq_event_t* _tmp20_;
					if (!_tmp18_) {
						if (!(snd_seq_event_input_pending (device, FALSE) > 0)) {
							break;
						}
					}
					_tmp18_ = FALSE;
					snd_seq_event_input (device, &_tmp19_);
					_snd_seq_free_event0 (event);
					event = _tmp19_;
					_tmp20_ = event;
					dumpMidiEvent (_tmp20_);
				}
			}
		}
		_snd_seq_free_event0 (event);
	}
	result = 0;
	_0 (device);
	return result;
}



